#![allow(clippy::unwrap_used)]

use std::sync::Arc;

use crate::domain::dynamic_entity::entity::DynamicEntity;
use crate::entity_definition::definition::EntityDefinition;
use crate::field::{FieldDefinition, FieldType};

use super::create_test_entity;

fn make_definition_with_required_field(field_name: &str) -> Arc<EntityDefinition> {
    let mut def = EntityDefinition::default();
    let mut field = FieldDefinition::new(
        field_name.to_string(),
        field_name.to_string(),
        FieldType::String,
    );
    field.required = true;
    def.fields.push(field);
    Arc::new(def)
}

#[test]
fn test_increment_version_increases_by_one() {
    let mut entity = create_test_entity();
    entity.increment_version().unwrap();
    let v: i64 = entity.get("version").unwrap();
    assert_eq!(v, 2);
}

#[test]
fn test_increment_version_twice() {
    let mut entity = create_test_entity();
    entity.increment_version().unwrap();
    entity.increment_version().unwrap();
    let v: i64 = entity.get("version").unwrap();
    assert_eq!(v, 3);
}

#[test]
fn test_increment_version_updates_updated_at() {
    let mut entity = create_test_entity();
    let before = entity.field_data.get("updated_at").unwrap().clone();
    // Small delay isn't reliable in unit tests; just assert the field still exists
    entity.increment_version().unwrap();
    assert!(entity.field_data.contains_key("updated_at"));
    // updated_at is always regenerated by increment_version
    let after = entity.field_data.get("updated_at").unwrap();
    // The value is a fresh timestamp — it must be a string
    assert!(
        after.is_string(),
        "updated_at should be a string, was: {after}"
    );
    drop(before);
}

#[test]
fn test_validate_passes_with_no_required_fields() {
    let entity = create_test_entity();
    assert!(entity.validate().is_ok());
}

#[test]
fn test_validate_fails_when_required_field_missing() {
    let definition = make_definition_with_required_field("title");
    let entity = DynamicEntity::new("typed".to_string(), definition);
    let result = entity.validate();
    assert!(result.is_err());
    assert!(result.unwrap_err().to_string().contains("title"));
}

#[test]
fn test_validate_passes_when_required_field_present() {
    let definition = make_definition_with_required_field("title");
    let mut entity = DynamicEntity::new("typed".to_string(), definition);
    entity.set("title", "My Title".to_string()).unwrap();
    assert!(entity.validate().is_ok());
}

#[test]
fn test_get_field_definition_returns_none_for_unknown() {
    let entity = create_test_entity();
    assert!(entity.get_field_definition("nonexistent").is_none());
}

#[test]
fn test_get_field_definition_returns_some_for_known() {
    let mut def = EntityDefinition::default();
    def.fields.push(FieldDefinition::new(
        "score".to_string(),
        "Score".to_string(),
        FieldType::Integer,
    ));
    let entity = DynamicEntity::new("scored".to_string(), Arc::new(def));
    assert!(entity.get_field_definition("score").is_some());
    assert_eq!(entity.get_field_definition("score").unwrap().name, "score");
}

#[test]
fn test_get_field_names_includes_system_fields() {
    let entity = create_test_entity();
    let names = entity.get_field_names();
    for expected in &[
        "uuid",
        "path",
        "created_at",
        "updated_at",
        "published",
        "version",
    ] {
        assert!(
            names.contains(&(*expected).to_string()),
            "missing system field: {expected}"
        );
    }
}

#[test]
fn test_get_field_names_includes_definition_fields() {
    let mut def = EntityDefinition::default();
    def.fields.push(FieldDefinition::new(
        "extra".to_string(),
        "Extra".to_string(),
        FieldType::String,
    ));
    let entity = DynamicEntity::new("typed".to_string(), Arc::new(def));
    assert!(entity.get_field_names().contains(&"extra".to_string()));
}
