/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyCreatedDialog: typeof import('@/modules/api-keys/components/ApiKeyCreatedDialog/index.vue')['default']
    ApiKeyCreateDialog: typeof import('@/modules/api-keys/components/ApiKeyCreateDialog/index.vue')['default']
    ApiKeyViewDialog: typeof import('@/modules/api-keys/components/ApiKeyViewDialog/index.vue')['default']
    Badge: typeof import('@/shared/components/Badge/index.vue')['default']
    ConfirmationDialog: typeof import('@/shared/components/ConfirmationDialog/index.vue')['default']
    CreateWorkflowDialog: typeof import('@/modules/workflows/components/CreateWorkflowDialog/index.vue')['default']
    DefaultPasswordBanner: typeof import('@/shared/components/DefaultPasswordBanner/index.vue')['default']
    DialogManager: typeof import('@/shared/components/DialogManager/index.vue')['default']
    DismissableBanner: typeof import('@/shared/components/DismissableBanner/index.vue')['default']
    DslConfigurator: typeof import('@/modules/workflows/components/DslConfigurator/index.vue')['default']
    EditWorkflowDialog: typeof import('@/modules/workflows/components/EditWorkflowDialog/index.vue')['default']
    EntityCreateDialog: typeof import('@/modules/entities/components/EntityCreateDialog/index.vue')['default']
    EntityDefinitionCreateDialog: typeof import('@/modules/entity-definitions/components/EntityDefinitionCreateDialog/index.vue')['default']
    EntityDefinitionDetails: typeof import('@/modules/entity-definitions/components/EntityDefinitionDetails/index.vue')['default']
    EntityDefinitionEditDialog: typeof import('@/modules/entity-definitions/components/EntityDefinitionEditDialog/index.vue')['default']
    EntityDefinitionFields: typeof import('@/modules/entity-definitions/components/EntityDefinitionFields/index.vue')['default']
    EntityDefinitionMetaInfo: typeof import('@/modules/entity-definitions/components/EntityDefinitionMetaInfo/index.vue')['default']
    EntityDefinitionTree: typeof import('@/modules/entity-definitions/components/EntityDefinitionTree/index.vue')['default']
    EntityDetails: typeof import('@/modules/entities/components/EntityDetails/index.vue')['default']
    EntityEditDialog: typeof import('@/modules/entities/components/EntityEditDialog/index.vue')['default']
    EntityPathPicker: typeof import('@/modules/entities/components/EntityPathPicker/index.vue')['default']
    EntityTree: typeof import('@/modules/entities/components/EntityTree/index.vue')['default']
    FieldEditor: typeof import('@/shared/forms/FieldEditor/index.vue')['default']
    IconPicker: typeof import('@/shared/components/IconPicker/index.vue')['default']
    LanguageSwitch: typeof import('@/shared/components/LanguageSwitch/index.vue')['default']
    LicenseBanner: typeof import('@/shared/components/LicenseBanner/index.vue')['default']
    LucideIcon: typeof import('@/shared/components/LucideIcon/index.vue')['default']
    MobileWarningBanner: typeof import('@/shared/components/MobileWarningBanner/index.vue')['default']
    NavigationSidebar: typeof import('@/shared/components/NavigationSidebar/index.vue')['default']
    PageLayout: typeof import('@/shared/components/PageLayout/index.vue')['default']
    PaginatedDataTable: typeof import('@/shared/tables/PaginatedDataTable/index.vue')['default']
    PermissionEditor: typeof import('@/modules/permissions/components/PermissionEditor/index.vue')['default']
    RoleDialog: typeof import('@/modules/permissions/components/RoleDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartIcon: typeof import('@/shared/components/SmartIcon/index.vue')['default']
    SnackbarManager: typeof import('@/shared/components/SnackbarManager/index.vue')['default']
    TreeView: typeof import('@/shared/components/TreeView/index.vue')['default']
    UserDialog: typeof import('@/modules/permissions/components/UserDialog/index.vue')['default']
    UserProfileMenu: typeof import('@/shared/components/UserProfileMenu/index.vue')['default']
    VersionHistory: typeof import('@/shared/components/VersionHistory/index.vue')['default']
    WorkflowFormFields: typeof import('@/modules/workflows/components/WorkflowFormFields/index.vue')['default']
    WorkflowLogsDialog: typeof import('@/modules/workflows/components/WorkflowLogsDialog/index.vue')['default']
    WorkflowRunDialog: typeof import('@/modules/workflows/components/WorkflowRunDialog/index.vue')['default']
  }
}
